/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 * @author Erick Gonzalez, Damian Cazarin & Aaron Alfonseca
 */
public class VistaPanelInicio extends javax.swing.JFrame {

    /**
     * Creates new form VistaPanelInicio
     */
    public VistaPanelInicio() {
        initComponents();

        //
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnVentas = new javax.swing.JButton();
        btnPedidos = new javax.swing.JButton();
        btnInformacion = new javax.swing.JButton();
        lblVentas = new javax.swing.JLabel();
        lblPedidos = new javax.swing.JLabel();
        lblInformacion = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        MenuOpciones = new javax.swing.JMenu();
        jMenuCerrarSesion = new javax.swing.JMenuItem();
        jMenuCambiarContraseña = new javax.swing.JMenuItem();
        jMenuFormulario = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Panel de Inicio");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Panel de inicio");

        btnVentas.setBackground(new java.awt.Color(242, 242, 242));
        btnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/icon_ventas32.png"))); // NOI18N
        btnVentas.setToolTipText("Realice ventas");
        btnVentas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btnVentas.setBorderPainted(false);
        btnVentas.setPreferredSize(new java.awt.Dimension(165, 149));
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });

        btnPedidos.setBackground(new java.awt.Color(242, 242, 242));
        btnPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/icon_pedidos32.png"))); // NOI18N
        btnPedidos.setToolTipText("Solicite pedidos de productos");
        btnPedidos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btnPedidos.setBorderPainted(false);

        btnInformacion.setBackground(new java.awt.Color(242, 242, 242));
        btnInformacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/icon_info32.png"))); // NOI18N
        btnInformacion.setToolTipText("Consulte informacion relacionada con la dulceria");
        btnInformacion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        btnInformacion.setBorderPainted(false);
        btnInformacion.setRequestFocusEnabled(false);

        lblVentas.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        lblVentas.setText("Panel de ventas");

        lblPedidos.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        lblPedidos.setText("Panel de pedidos");

        lblInformacion.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        lblInformacion.setText("Panel de información");

        MenuOpciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/icon_opciones16.png"))); // NOI18N
        MenuOpciones.setText("Opciones");
        MenuOpciones.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N

        jMenuCerrarSesion.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jMenuCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/icon_logout16.png"))); // NOI18N
        jMenuCerrarSesion.setText("Cerrar sesión");
        MenuOpciones.add(jMenuCerrarSesion);

        jMenuCambiarContraseña.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jMenuCambiarContraseña.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/icon_password16.png"))); // NOI18N
        jMenuCambiarContraseña.setText("Cambiar contraseña");
        MenuOpciones.add(jMenuCambiarContraseña);

        jMenuFormulario.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jMenuFormulario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graficos/icon_users16.png"))); // NOI18N
        jMenuFormulario.setText("Agregar, Modificar o Eliminar Usuarios");
        MenuOpciones.add(jMenuFormulario);

        jMenuBar2.add(MenuOpciones);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInformacion)
                    .addComponent(lblPedidos)
                    .addComponent(lblVentas))
                .addContainerGap(50, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lblVentas)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblPedidos)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lblInformacion)))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        btnInformacion.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVentasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPanelInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPanelInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPanelInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPanelInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        try {
            UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");
        } catch (ClassNotFoundException ex) {
            //Logger.getLogger(VistaInicio.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            //Logger.getLogger(VistaInicio.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            //Logger.getLogger(VistaInicio.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            // Logger.getLogger(VistaInicio.class.getName()).log(Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPanelInicio().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenu MenuOpciones;
    public javax.swing.JButton btnInformacion;
    public javax.swing.JButton btnPedidos;
    public javax.swing.JButton btnVentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar2;
    public javax.swing.JMenuItem jMenuCambiarContraseña;
    public javax.swing.JMenuItem jMenuCerrarSesion;
    public javax.swing.JMenuItem jMenuFormulario;
    public javax.swing.JLabel lblInformacion;
    public javax.swing.JLabel lblPedidos;
    public javax.swing.JLabel lblVentas;
    // End of variables declaration//GEN-END:variables

}
